services:
  db:
    image: postgres:17.6
    container_name: catdex
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./internal/scripts:/docker-entrypoint-initdb.d
    ports:
      - "5434:5432"

volumes:
  db-data:
